### ISSUE TITLE
[TYPO] xtan(theta)

### ISSUE THREAD

**Issue by Nichodon** [anematode/gatm#28] opened 2020-03-02 22:33 UTC
Reported by the Edmund Lam:
Page 33 contains references to a line `y=tan(theta/2)` (and other similar expressions) that do not have an `x`. Perhaps a typo?

**Comment by SheepTester** [comment] 2020-03-07 01:36
Duplicate of #27, fixed in d31f92a104400f37b448f6c03084f72fba693515

**Closed** 2020-03-14 03:43 UTC
Labels: bug
